### ISSUE TITLE
dockerのnodeのコンテナってローカル開発環境で使われてますか?

### ISSUE THREAD

**Issue by rchaser53** [insidefrontend/issue2-ama#14]
# Issueのタイトル
dockerのnodeのコンテナってローカル開発環境で使われてますか?

# 質問をしたいAMAブース
- [x] AbemaTVだけど質問ある？（AbemaTV関係ない質問でもいいです）by Kenichi Kato, Tetsuharu OHZEKI, and Shota Kubota

# 質問
フロントエンド開発でdockerのnodeのコンテナって使われていますか。CI環境とローカルの開発環境を近づけられたらと思いnodeのコンテナの使用を検討しています。もし使っていたら話を聞けると嬉しいです。

**Comment by becyn** [comment]
使っています。
ただし、本番のイメージをそのまま使ってなく、マイナーチェンジ（デバックのポートを開けている、環境変数を足している）しています。

本番の方はKubernetesですが、localでは、docker-composeで動かしています。

**Comment by becyn** [comment]
## Q. トラブルは起こってない？
ローカル開発環境としても、今のところは起こってないです。トラブルがあっても、一度止めて立ち上げたらだいたい直っているので、特に対応しないといけないトラブルは起こっていません。

**Comment by becyn** [comment]
## Q. DockerのNodeイメージってalpineごにょごにょしたんですか？
Alpine node引っ張ってきています。そんなにいじってないですが、yarnをいれたりしています。

**Comment by rchaser53** [comment]
ありがとうございます。Closeします。
