### ISSUE TITLE
storybookと単体テスト

### ISSUE THREAD

**Issue by miyanokomiya** [insidefrontend/issue2-ama#39]
# コンポーネント座談会

コンポーネントに関する質問をY!のReact・Vue・Angular勢のそれぞれの視点でお答えします。また「うちはこうしてる」も大歓迎なので、一緒に議論しましょう。

- @pirosikick（Yahoo! JAPAN / リッチラボ株式会社）
- @koh110（Yahoo! JAPAN）
- @ikasumiwt（Yahoo! JAPAN）

## 質問

コンポーネントは要素は見た目部分が多く単体テストは諦めてstorybookによる手動の見た目確認と動作確認で現在は妥協しています。storybookは見た目のみで、見た目以外の部分はやはり単体テストするほうが効果的でしょうか？

**Comment by p1xb1t** [comment]
# 回答
**伊藤さん：** 無理になんでも自動化するよりも、手動でやるほうがコストが低ければ手動でやる方が良い。
**穴井さん：** json-schemaを利用する場合など、コンポーネントにロジックを入れざるを得ない場合もあるが、基本的にstorybookで確認できるようなコンポーネントならば、ロジックを含まずstorybook内で確認できるほうが良いと思う。スクショ撮ってdiffを撮るなどは出来るが、それ以上となると難しい。
**加藤さん：** コンポーネントのテストは見た目が主ではなく、どういう時にどういう振る舞いをするか、ということがベース。そのため、見た目のテストと単体テストは分けたほうが良い。
